@api = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjE1LCJ0dW5hSUQiOjEsInJvbGUiOiJhZG1pblR1bmEiLCJpYXQiOjE2NTY3NzM5NzUsImV4cCI6MTY1NzMxMzk3NX0.AdoxGnzWGClQzjbhMZ3GVK_mR7NIZz4KOIUPwNuknoY

### 
GET {{api}}/events
Authorization: {{token}}


###
GET {{api}}/tunas/1/events/2

###
POST {{api}}/events
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Cena en Casa Julia",
    "description": "Descripcion del evento",
    "creator": "14",
    "date": "2017-02-01",
    "tuna": "1"
}

###
GET {{api}}/events/33/users