@api = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjE1LCJ0dW5hSUQiOjEsInJvbGUiOiJhZG1pblR1bmEiLCJpYXQiOjE2NTY3OTc5NTEsImV4cCI6MTY1NzMzNzk1MX0.AbUg8FJlyAHKGP0VirGHPkPK6PF3bHdQfnHAkrCiO7o
### Pedir todas las canciones de una tuna
GET {{api}}/tunas/songs/getall
Authorization: {{token}}


### One song from one Tuna
GET {{api}}/tunas/1/songs/1

### Crear una canción
POST {{api}}/tunas/1/songs
Content-Type: application/json

{
    "name": "Alicantina",
    "author": "Carlos Berrueco",
    "lastEditor": 4,
    "lyrics": "Cuando estoy lejos recuerdo recuerdo \n mi inigualable ciudad \n solo de pensarlo quiero \n por mi Alicante llorar."
}

### Actualizar letra de una canción indicando id de la canción
PUT {{api}}/songs/1/updateLyrics
Content-Type: application/json

{
    "lyrics": "Moci[LAm]ta, da[MI]me el clavel[LAm],\ndame el clavel de tu[MI] boca"
}

### Delete a song by id
DELETE {{api}}/songs/2