@api = http://localhost:3000

### Pedir todas las tunas
GET {{api}}/tunas
### Pedir una tuna
GET {{api}}/tunas/1

### Crear una tuna
POST {{api}}/tunas
Content-Type: application/json

{
    "name": "Tuna de Derecho de Alicante",
    "ShortName": "TDA"
}
### Devuelve número de usuarios de una tuna
GET {{api}}/tunas/1/countofusers
### Borrar una tuna
DELETE {{api}}/tunas/15
###
DELETE {{api}}/tunas