@api = http://localhost:3000

GET {{api}}/users

### Pedir todos los usuarios de una tuna
GET {{api}}/tunas/1/users

### Get one user by id
GET {{api}}/users/1


### Crear un usuario en una tuna
Post {{api}}/tunas/1/users
Content-Type: application/json

{
    "Name": "Ruperto",
    "Email": "ru@correo.es",
    "Mote": "El Fiera",
    "Password": "123456"
}

### Update password of an user 
PUT {{api}}/users/1/update_password
Content-Type: application/json

{
    "Password": "pass"
}

### Modificar mote de un usuario
PUT {{api}}/users/1/update_mote
Content-Type: application/json

{
    "Mote": "Frijol"
}

### Update user role
PUT {{api}}/users/1/update_role
Content-Type: application/json

{
    "Role": "admin"
}

### Delete user
DELETE {{api}}/users/7

### Create user
POST {{api}}/users
Content-Type: application/json

{
    "name": "Carlos Vidal",
    "email": "cvi1@alu.ua.es",
    "mote": "El 64",
    "tunaid": 1,
    "password": "123456"
}

###
POST {{api}}/users/login
Content-Type: application/json

{
    "email": "cvi1@alu.ua.es",
    "password": "123456"
}

